version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - sam build
      - sam package --s3-bucket $ARTIFACT_BUCKET --output-template-file packaged.yaml --region $AWS_DEFAULT_REGION
      - sam deploy --template-file packaged.yaml --stack-name $STACK_NAME --capabilities CAPABILITY_IAM --no-confirm-changeset --no-fail-on-empty-changeset --s3-bucket $ARTIFACT_BUCKET --region $AWS_DEFAULT_REGION

  post_build:
    commands:
      - echo "Getting API URL..."
artifacts:
  files:
    - packaged.yaml
